Added: comment that Windows containers not yet supported in vNet
Azure/terraform-azurerm-aci-devops-agent pull request #16
Opened 2021-02-08 21:15 UTC by james-flynn-ie

Windows containers are not yet supported in a container group in a Virtual Net (https://docs.microsoft.com/en-us/azure/container-instances/container-instances-virtual-network-concepts#other-limitations)

Adding this note as it cost me some time to implement the module and then receive the message that it isn't supported at present.

2021-02-10 09:38 UTC, jcorioland requested changes
Hi @james-flynn-ie - thank you for your contribution. As the entire section is titled "Deploy Linux agents" I suggest we had a note in the begining to make clear it apply only to Linux. Instead of at the end of the paragraph like you suggested.
Once you apply the suggested changes, if you accept, I'll merge the PR :-)

2021-02-10 09:38 UTC, jcorioland commented on README.md
```suggestion
*Note: Virtual Network integration is only supported for Linux Containers in ACI. This part [does not apply to Windows Containers](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-virtual-network-concepts#other-limitations).*
```

2021-02-10 09:38 UTC, jcorioland commented on README.md
> +The configuration below can be used to deploy Azure DevOps agents in Linux containers, in an existing virtual network. Windows containers are not yet supported in a container group deployed to a Virt
```suggestion
The configuration below can be used to deploy Azure DevOps agents in Linux containers, in an existing virtual network.
```

2021-02-10 18:10 UTC, james-flynn-ie commented
Thank you for the suggested changes @jcorioland, they've been committed now. :+1:

2021-02-11 08:01 UTC, jcorioland approved these changes

2021-02-11 08:02 UTC, merged